spring:
  application:
    name: kopic-ge

engine:
  endpoint: http://localhost:8080

room-runner:
  workers: 4
  scheduler-workers: 2

session-presence:
  redis-key-prefix: "session:presence:user:"
  cache-ttl-seconds: 5

grpc:
  server:
    port: 9090
